version: "3.9"

services:
  api:
    build: .
    container_name: wunderlist-api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      APP_ENV: development
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: wunderlist
      JWT_SECRET: super-secret
      JWT_ACCESS_TTL_MIN: 15
      JWT_REFRESH_TTL_HOURS: 168
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: wunderlist-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
