version: "3.9"

services:
  api:
    build: .
    container_name: wunderlist-api
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development

      JWT_SECRET: dev-access-secret
      JWT_REFRESH_SECRET: dev-refresh-secret

      MONGO_URI: mongodb://mongo:27017/wunderlist
      MONGO_DB: wunderlist

      REDIS_ADDR: redis:6379

    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: wunderlist-mongo
    volumes:
      - mongo-data:/data/db
    # ❌ no ports exposed

  redis:
    image: redis:7-alpine
    container_name: wunderlist-redis
    # ❌ no ports exposed

volumes:
  mongo-data:
